name: HorizonsGears
version: ${project.version}
author: GidorStudios
description: A generic Slimefun4-Addon
website: https://github.com/Slimefun/Addon-Template

main: me.gidorstudios.horizonsgears.HorizonsGears
depend: [Slimefun]

api-version: 1.14